### ISSUE TITLE
panic: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by RulerOf** [opsgenie/opsgenie-heartbeat#5]
A couple of days ago, we started having intermittent failure of the script monitor with the error message shown in the subject. It's happening every time we run it now, and the heartbeats are not being updated at all. 

We run it like this via a bash script where the invocation is similar to:

```shell
./oghb-linux-amd64 \
-apiKey my-api-key-here \
-name "My Job Name" \
-description "My Job's Description" \
-intervalUnit hours \
-timetoexpire 36 \
-action start
```

The full error output:

```
panic: invalid character '<' looking for beginning of value

goroutine 1 [running]:
panic(0x724440, 0xc8204460a0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
main.createErrorResponse(0xc8203cd800, 0x227, 0x600, 0x0, 0x0, 0x0)
	/Users/mt/dev/go/src/github.com/opsgenie/opsgenie-heartbeat/script monitor/src/oghb.go:184 +0x106
main.getHeartbeat(0x10000000a)
	/Users/mt/dev/go/src/github.com/opsgenie/opsgenie-heartbeat/script monitor/src/oghb.go:84 +0x44d
main.startHeartbeat()
	/Users/mt/dev/go/src/github.com/opsgenie/opsgenie-heartbeat/script monitor/src/oghb.go:61 +0x18
main.main()
	/Users/mt/dev/go/src/github.com/opsgenie/opsgenie-heartbeat/script monitor/src/oghb.go:28 +0x76
```

I got the same result when testing this on Centos 6.9 and OS X 10.12.5. 

Some light googling suggested that the code may be trying to parse HTML where it is expecting to receive something like JSON via an API call.

**Comment by halitokumus** [comment]
Hi, thanks for reporting this we'll  upgrade the API oghb uses and check.

**Comment by RulerOf** [comment]
Hacking away at Golang stuff is painfully slow for me, but here's what was in the ResponseBody text that's passed to createErrorResponse():

```HTML
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Bad request.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: 0dYzC5O2dG7yutdv_yIB_0QxzHkQEzyKqXrKWpqBpIEEuFWNJvhbyA==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```

**Comment by halitokumus** [comment]
Do you have the StatusCode value?

**Comment by RulerOf** [comment]
I was able to find it, it's coming back as a 403.

I used Burp Proxy to intercept the request, and this equivalent cURL command can reproduce the error:

```shell
curl -i -s -k  -X $'GET' \
    -H $'User-Agent: Go-http-client/1.1' \
    --data-binary $'null' \
    $'https://api.opsgenie.com/v1/json/heartbeat/?apiKey=MY-API-KEY-HERE&name=MY+HEARTBEAT+NAME'
```

**Comment by RulerOf** [comment]
Removing the null body fixes it.  I'll see if I can do that with the Go code
